name: Node.js CI/CD Deploy

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22

          script: |
            set -e

            cd ~/express-devops

            echo "Pulling latest code..."
            git fetch origin main
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm ci --omit=dev

            echo "Restarting application..."
            pm2 restart express-devops

            echo "Deployment completed!"
            pm2 status
